# Numpy Package

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([0,2,5,4,5])

## Common Items in a Numpy arrays

In [3]:
common_item = np.intersect1d(a,b)
print(common_item)

[2 4 5]


## Common Items indices

In [ ]:
print(np.where(a==b))

(array([1, 3, 4], dtype=int64),)


## Filtering an Array with Where()

In [61]:
indices=np.where((2<=a) & (a<=5))
result = a[indices]

print(result)

[2 3 4 5]
