In [2]:
!pip install numpy

In [3]:
import numpy as np

# 1. Create

In [4]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), -1)
ones = np.ones((2,2,2))
full

array([[[-1, -1],
        [-1, -1]],

       [[-1, -1],
        [-1, -1]]])

In [5]:
type(ones)

numpy.ndarray

In [6]:
data

array([[[0.72537542, 0.2396    , 0.00624761, 0.59862659],
        [0.82409168, 0.03819772, 0.79670395, 0.0939198 ],
        [0.91602224, 0.82140001, 0.91905594, 0.40314368]],

       [[0.4829657 , 0.14379903, 0.24434039, 0.82191755],
        [0.3874462 , 0.19203127, 0.20857411, 0.16842186],
        [0.96708922, 0.16532174, 0.72065323, 0.67023551]]])

In [7]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
full

array([[[-1, -1],
        [-1, -1]],

       [[-1, -1],
        [-1, -1]]])

In [10]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
arr = np.array([[1,2],[1,2]])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr

array([[1, 2],
       [1, 2]])

# 2. Read

In [14]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [16]:
size

24

In [36]:
# Slicing
arr = data[1][1][3]
slicer = data[0][2][0:2]
reverse = data[-1][-3][0]
singleval = data[0][0][0]

In [37]:
reverse

0.5321376525859042

In [39]:
data

array([[[0.72833212, 0.79963635, 0.95654337, 0.11745646],
        [0.46217238, 0.20830138, 0.04354799, 0.41218107],
        [0.09291454, 0.98260479, 0.85936967, 0.24624239]],

       [[0.53213765, 0.06560753, 0.44020056, 0.21303124],
        [0.51586371, 0.14366324, 0.79015415, 0.92238884],
        [0.43189992, 0.52789158, 0.46113548, 0.86414634]]])

In [38]:
data[0][0:2]

array([[0.72833212, 0.79963635, 0.95654337, 0.11745646],
       [0.46217238, 0.20830138, 0.04354799, 0.41218107]])

# 3. Update

In [19]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [ ]:
print(list1)
print(list2)

[0.91859167 1.81667633 0.67283356 0.45362365 0.6956376  1.02143568
 1.14479545 0.10933102 0.45065317 0.73698532]
[0.02392472 0.93395513 0.4158901  0.16119296 0.54743991 0.14703506
 0.46126101 0.01584386 0.13825848 0.68141625]


In [47]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)
add
sub
div
dot

1.9179046905667985

In [50]:
dot    
[1 2    
3 4]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (220912851.py, line 2)

In [54]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(data)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)
exp

array([ 7.3890561 , 20.08553692])

In [34]:
log

array([[[-0.45727825, -1.73762976, -2.00149388, -1.65196187],
        [-0.35421361, -0.80605596, -0.56030619, -0.46647907],
        [-0.6915376 , -0.6178291 , -3.23883703, -0.11040235]],

       [[-0.03204431, -2.09456467, -0.87270946, -1.41305019],
        [-0.28078646, -3.93375834, -1.0478005 , -0.05282794],
        [-0.91106737, -3.19516244, -0.69009193, -0.04082848]]])

In [14]:
data

array([[[0.01038681, 0.21787218, 0.42851835, 0.64881025],
        [0.19335512, 0.21826725, 0.01899688, 0.76551894],
        [0.177093  , 0.20436728, 0.87188558, 0.22251969]],

       [[0.70927591, 0.34284349, 0.09135198, 0.4352562 ],
        [0.70341639, 0.2321961 , 0.13272667, 0.24661041],
        [0.34284819, 0.8144995 , 0.81043251, 0.66375411]]])

In [21]:
data[0][0][0] = 100

In [22]:
data

array([[[1.00000000e+02, 9.94548891e-01, 8.23698032e-01, 1.67781910e-01],
        [5.73940933e-01, 2.73830804e-01, 3.66586308e-01, 7.88158797e-01],
        [4.37105684e-01, 3.36140172e-01, 3.24169519e-01, 2.88250474e-01]],

       [[4.49031394e-01, 1.47322595e-01, 7.49536334e-01, 2.33479732e-02],
        [9.31314353e-01, 6.66111029e-01, 5.60221160e-01, 4.77946807e-01],
        [6.86652987e-01, 6.64581853e-01, 1.73953700e-01, 3.51192377e-01]]])

In [57]:
data.sort()
data

array([[[1.17456456e-01, 7.99636349e-01, 9.56543373e-01, 7.00000000e+02],
        [4.35479923e-02, 2.08301381e-01, 4.12181071e-01, 4.62172385e-01],
        [9.29145422e-02, 2.46242387e-01, 8.59369665e-01, 9.82604790e-01]],

       [[6.56075289e-02, 2.13031244e-01, 4.40200557e-01, 5.32137653e-01],
        [1.43663245e-01, 5.15863708e-01, 7.90154155e-01, 9.22388837e-01],
        [4.31899920e-01, 4.61135477e-01, 5.27891582e-01, 8.64146342e-01]]])

In [58]:
print(data.shape)

(2, 3, 4)


In [59]:
data = data.reshape((24,1))
data.shape

(24, 1)

In [60]:
data

array([[1.17456456e-01],
       [7.99636349e-01],
       [9.56543373e-01],
       [7.00000000e+02],
       [4.35479923e-02],
       [2.08301381e-01],
       [4.12181071e-01],
       [4.62172385e-01],
       [9.29145422e-02],
       [2.46242387e-01],
       [8.59369665e-01],
       [9.82604790e-01],
       [6.56075289e-02],
       [2.13031244e-01],
       [4.40200557e-01],
       [5.32137653e-01],
       [1.43663245e-01],
       [5.15863708e-01],
       [7.90154155e-01],
       [9.22388837e-01],
       [4.31899920e-01],
       [4.61135477e-01],
       [5.27891582e-01],
       [8.64146342e-01]])

In [61]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [62]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [54]:
data

array([[0.63300418],
       [0.17593692],
       [0.13513326],
       [0.1916735 ],
       [0.70172506],
       [0.44661607],
       [0.57103419],
       [0.62720674],
       [0.50080544],
       [0.53911353],
       [0.03920947],
       [0.89547377],
       [0.96846367],
       [0.12312383],
       [0.41781795],
       [0.24339973],
       [0.75518958],
       [0.01956998],
       [0.35070828],
       [0.9485432 ],
       [0.40209481],
       [0.04095987],
       [0.50152996],
       [0.95999378]])

In [63]:
np.delete(data, 0, axis=1)

array([], shape=(24, 0), dtype=float64)

In [64]:
data.shape

(24, 1)

In [65]:
data

array([[1.17456456e-01],
       [7.99636349e-01],
       [9.56543373e-01],
       [7.00000000e+02],
       [4.35479923e-02],
       [2.08301381e-01],
       [4.12181071e-01],
       [4.62172385e-01],
       [9.29145422e-02],
       [2.46242387e-01],
       [8.59369665e-01],
       [9.82604790e-01],
       [6.56075289e-02],
       [2.13031244e-01],
       [4.40200557e-01],
       [5.32137653e-01],
       [1.43663245e-01],
       [5.15863708e-01],
       [7.90154155e-01],
       [9.22388837e-01],
       [4.31899920e-01],
       [4.61135477e-01],
       [5.27891582e-01],
       [8.64146342e-01]])

In [67]:
np.save("new array", data)

In [68]:
test = np.load("new array.npy")

In [69]:
test

array([[1.17456456e-01],
       [7.99636349e-01],
       [9.56543373e-01],
       [7.00000000e+02],
       [4.35479923e-02],
       [2.08301381e-01],
       [4.12181071e-01],
       [4.62172385e-01],
       [9.29145422e-02],
       [2.46242387e-01],
       [8.59369665e-01],
       [9.82604790e-01],
       [6.56075289e-02],
       [2.13031244e-01],
       [4.40200557e-01],
       [5.32137653e-01],
       [1.43663245e-01],
       [5.15863708e-01],
       [7.90154155e-01],
       [9.22388837e-01],
       [4.31899920e-01],
       [4.61135477e-01],
       [5.27891582e-01],
       [8.64146342e-01]])